### ISSUE TITLE
Wrong export for schnorr signatures

### ISSUE THREAD

**Issue by prolic** [haskell-bitcoin/libsecp256k1-haskell#8]
I made it work with this:

```
-- Function to extract ByteString from Signature
signatureToByteString :: Signature -> IO BS.ByteString
signatureToByteString (Signature (S.Signature fptr)) =
    withForeignPtr fptr $ \ptr -> BS.create sigSize $ \destPtr -> do
        let bytePtr = castPtr ptr :: Ptr Word8  -- Cast Ptr Prim.Sig64 to Ptr Word8
        bytes <- peekArray sigSize bytePtr      -- Read the bytes from the casted pointer
        -- Copy bytes into destination pointer
        mapM_ (\(i, b) -> pokeElemOff destPtr i b) (zip [0..] bytes)
```

using ecdsaSignatureSerializeCompact gives wrong results.

**Comment by prolic** [comment]
@wraithm @ProofOfKeags

**Comment by ProofOfKeags** [comment]
What do you mean by "gives wrong results" how did you observe this behavior?

I took a look at the code you provided but as far as I can tell all it does is copy the underlying buffer.

**Comment by ProofOfKeags** [comment]
Also it's worth noting that using `ecdsaSignatureSerializeCompact` is unlikely to work with Schnorr sigs.

**Comment by prolic** [comment]
That's my point, I can't export the schnorr signatures to bytestring (or
hex). If you want, I can submit a pull request by tomorrow.

**Comment by ProofOfKeags** [comment]
If you want to submit a PR feel free. Otherwise I'll take care of it this week. It looks like we need to mark signatures internally by what kind they are and then export them accordingly. From there we also need to modify the import function to accept a hint about what kind of signature it is, since there isn't a structural difference between ecdsa sigs and schnorr sigs when parsing them.
